In this study we will complete the whole Exercise with Numpy.


#### 1. Import NumPy Library

In [1]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [2]:
my_list=[5,10,15,20,25]
np.array(my_list)

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [3]:
# CODE HERE
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [4]:
np.ones((4,4),dtype='int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [5]:
np.ones((4,4),dtype='int')*7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

In [6]:
np.full((4,4),7,dtype='int')

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [7]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [8]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [9]:
np.linspace(0,25,25,dtype='int',endpoint=False).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create 5 random number with numpy

In [10]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

#### 11. Create random normal distributed 5x5 array

In [12]:
np.random.seed(42)
np.random.randn(5,5)

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337],
       [-0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004],
       [-0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783],
       [-0.56228753, -1.01283112,  0.31424733, -0.90802408, -1.4123037 ],
       [ 1.46564877, -0.2257763 ,  0.0675282 , -1.42474819, -0.54438272]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [14]:
np.random.seed(42)
np.random.randint(20,50,size=(3,4))

array([[26, 39, 48, 34],
       [30, 27, 48, 40],
       [26, 45, 38, 42]])

#### 13. Reshape the array below with shape 6x8

In [16]:
np.random.seed(42)
ranarr = np.random.randint(0, 60, 48)
ranarr

array([38, 51, 28, 14, 42,  7, 20, 38, 57, 18, 22, 10, 10, 23, 52, 35, 39,
       23,  2, 21, 52,  1, 23, 43, 29, 37,  1, 59, 20, 32, 11, 57, 21, 43,
       24, 48, 26, 58, 41, 27, 59, 15, 14, 46, 50, 43, 54, 51])

In [17]:
ranarr.reshape(6,8)

array([[38, 51, 28, 14, 42,  7, 20, 38],
       [57, 18, 22, 10, 10, 23, 52, 35],
       [39, 23,  2, 21, 52,  1, 23, 43],
       [29, 37,  1, 59, 20, 32, 11, 57],
       [21, 43, 24, 48, 26, 58, 41, 27],
       [59, 15, 14, 46, 50, 43, 54, 51]])

In [18]:
ranarr.reshape(-1,8)

array([[38, 51, 28, 14, 42,  7, 20, 38],
       [57, 18, 22, 10, 10, 23, 52, 35],
       [39, 23,  2, 21, 52,  1, 23, 43],
       [29, 37,  1, 59, 20, 32, 11, 57],
       [21, 43, 24, 48, 26, 58, 41, 27],
       [59, 15, 14, 46, 50, 43, 54, 51]])

## Numpy Indexing and Selection


In [19]:
mat = np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [20]:
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [21]:
mat[:,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [22]:
mat[1,::2]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [23]:
mat[:,2]=77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [24]:
mat[[1,3],[0,1]]

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [25]:
mat[1::2,0::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 in mat

In [27]:
mat[mat<10]

array([1, 2, 4, 5, 6, 8, 9])

In [28]:
mat[mat>12]

array([77, 77, 77, 13, 14, 77, 16])

In [29]:
mat[mat<10]+mat[mat>12]

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [32]:
(mat[mat<10]+mat[mat>12]).std()

29.700546274093877

#### 22. Get the sum of second column in mat

In [33]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [34]:
mat[:,2]=[3,7,11,15]

In [35]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [36]:
mat[:,1].sum(axis=0)

32

#### 23. Get the median,mean and std of 3rd row in mat

In [38]:
np.median(mat[2])

10.5

In [39]:
np.mean(mat[2])

10.5

In [43]:
np.std(mat[2])

1.118033988749895